apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    glance.description: IT tools for everyday use
    glance.name: IT Tools
    glance.url: http://192.168.68.204:8083
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: it-tools
  name: it-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: it-tools
  template:
    metadata:
      annotations:
        glance.description: IT tools for everyday use
        glance.name: IT Tools
        glance.url: http://192.168.68.204:8083
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: it-tools
    spec:
      containers:
        - image: corentinth/it-tools:latest
          name: it-tools
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
