apiVersion: v1
kind: Service
metadata:
  annotations:
    glance.description: IT tools for everyday use
    glance.name: IT Tools
    glance.url: http://192.168.68.204:8083
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: it-tools
  name: it-tools
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 80
  selector:
    io.kompose.service: it-tools
